const PUZZLES = {
  easy: [
    { word: "BRAIN", letters: ["B","R","A","I","N","E","T","S"] },
    { word: "FLAME", letters: ["F","L","A","M","E","R","T","S"] },
    { word: "GLOBE", letters: ["G","L","O","B","E","R","N","T"] },
    { word: "CLIMB", letters: ["C","L","I","M","B","A","E","T"] },
    { word: "DRAFT", letters: ["D","R","A","F","T","E","I","S"] },
    { word: "GLARE", letters: ["G","L","A","R","E","N","T","S"] },
    { word: "FROWN", letters: ["F","R","O","W","N","A","E","T"] },
    { word: "GRACE", letters: ["G","R","A","C","E","I","N","T"] },
    { word: "GRAND", letters: ["G","R","A","N","D","E","T","S"] },
    { word: "GRIND", letters: ["G","R","I","N","D","A","E","T"] },
    { word: "GROVE", letters: ["G","R","O","V","E","A","N","T"] },
    { word: "GROAN", letters: ["G","R","O","A","N","E","T","S"] },
    { word: "GRANT", letters: ["G","R","A","N","T","E","I","S"] },
    { word: "GRASP", letters: ["G","R","A","S","P","E","N","T"] },
    { word: "BRAVE", letters: ["B","R","A","V","E","N","T","S"] },
    { word: "BRAND", letters: ["B","R","A","N","D","E","T","S"] },
    { word: "BRACE", letters: ["B","R","A","C","E","N","T","S"] },
    { word: "BREAD", letters: ["B","R","E","A","D","N","T","S"] },
    { word: "BREAK", letters: ["B","R","E","A","K","N","T","S"] },
    { word: "BLEND", letters: ["B","L","E","N","D","A","T","S"] },
    { word: "BLAZE", letters: ["B","L","A","Z","E","N","T","S"] },
    { word: "BLAND", letters: ["B","L","A","N","D","E","T","S"] },
    { word: "BLANK", letters: ["B","L","A","N","K","E","T","S"] },
    { word: "BLAST", letters: ["B","L","A","S","T","E","N","R"] },
    { word: "BLOAT", letters: ["B","L","O","A","T","E","N","S"] },
    { word: "BLOOD", letters: ["B","L","O","O","D","A","N","T"] },
    { word: "BLOWN", letters: ["B","L","O","W","N","A","E","T"] },
    { word: "BLUNT", letters: ["B","L","U","N","T","A","E","S"] },
    { word: "BOOST", letters: ["B","O","O","S","T","A","E","N"] },
    { word: "BOUND", letters: ["B","O","U","N","D","A","E","T"] },
    { word: "BOXER", letters: ["B","O","X","E","R","A","N","T"] },
    { word: "BRICK", letters: ["B","R","I","C","K","A","E","T"] },
    { word: "BRISK", letters: ["B","R","I","S","K","A","E","T"] },
    { word: "BROTH", letters: ["B","R","O","T","H","A","E","N"] },
    { word: "BROWN", letters: ["B","R","O","W","N","A","E","T"] },
    { word: "BRUSH", letters: ["B","R","U","S","H","A","E","T"] },
    { word: "BUILT", letters: ["B","U","I","L","T","A","E","N"] },
    { word: "BULGE", letters: ["B","U","L","G","E","A","N","T"] },
    { word: "BUNCH", letters: ["B","U","N","C","H","A","E","T"] },
    { word: "BURST", letters: ["B","U","R","S","T","A","E","N"] },
    { word: "CABLE", letters: ["C","A","B","L","E","R","N","T"] },
    { word: "CADGE", letters: ["C","A","D","G","E","R","N","T"] },
    { word: "CAMEL", letters: ["C","A","M","E","L","R","N","T"] },
    { word: "CANAL", letters: ["C","A","N","A","L","R","E","T"] },
    { word: "CARGO", letters: ["C","A","R","G","O","E","N","T"] },
    { word: "CARRY", letters: ["C","A","R","R","Y","E","N","T"] },
    { word: "CARVE", letters: ["C","A","R","V","E","N","T","S"] },
    { word: "CLASH", letters: ["C","L","A","S","H","E","N","T"] },
    { word: "CLASP", letters: ["C","L","A","S","P","E","N","T"] },
    { word: "CLEAN", letters: ["C","L","E","A","N","R","T","S"] },
    { word: "CLEAR", letters: ["C","L","E","A","R","N","T","S"] },
    { word: "CLERK", letters: ["C","L","E","R","K","A","N","T"] },
    { word: "CLIMB", letters: ["C","L","I","M","B","A","E","T"] },
    { word: "CLINK", letters: ["C","L","I","N","K","A","E","T"] },
    { word: "CLOCK", letters: ["C","L","O","C","K","A","E","N"] },
    { word: "CLONE", letters: ["C","L","O","N","E","A","R","T"] },
    { word: "CLOSE", letters: ["C","L","O","S","E","A","N","T"] },
    { word: "CLOUD", letters: ["C","L","O","U","D","A","N","T"] },
    { word: "CLOWN", letters: ["C","L","O","W","N","A","E","T"] },
    { word: "COACH", letters: ["C","O","A","C","H","R","E","T"] },
  ],
  medium: [
    { word: "BRANCH", letters: ["B","R","A","N","C","H","E","T","S","L"] },
    { word: "BRIDGE", letters: ["B","R","I","D","G","E","A","N","T","S"] },
    { word: "BRIGHT", letters: ["B","R","I","G","H","T","A","E","N","S"] },
    { word: "BRONZE", letters: ["B","R","O","N","Z","E","A","T","S","L"] },
    { word: "BRUTAL", letters: ["B","R","U","T","A","L","E","N","S","I"] },
    { word: "BUBBLE", letters: ["B","U","B","B","L","E","A","N","T","S"] },
    { word: "BUDGET", letters: ["B","U","D","G","E","T","A","N","S","L"] },
    { word: "BUNDLE", letters: ["B","U","N","D","L","E","A","T","S","R"] },
    { word: "CACTUS", letters: ["C","A","C","T","U","S","E","N","R","L"] },
    { word: "CASTLE", letters: ["C","A","S","T","L","E","R","N","I","B"] },
    { word: "CATTLE", letters: ["C","A","T","T","L","E","R","N","S","I"] },
    { word: "CAUGHT", letters: ["C","A","U","G","H","T","R","E","N","S"] },
    { word: "CAVERN", letters: ["C","A","V","E","R","N","S","T","L","I"] },
    { word: "CELLAR", letters: ["C","E","L","L","A","R","S","T","N","I"] },
    { word: "CEMENT", letters: ["C","E","M","E","N","T","A","R","S","L"] },
    { word: "CENTER", letters: ["C","E","N","T","E","R","A","S","L","I"] },
    { word: "CHARGE", letters: ["C","H","A","R","G","E","N","T","S","L"] },
    { word: "CHASER", letters: ["C","H","A","S","E","R","N","T","L","I"] },
    { word: "CHISEL", letters: ["C","H","I","S","E","L","A","N","T","R"] },
    { word: "CHOICE", letters: ["C","H","O","I","C","E","N","T","S","L"] },
    { word: "CHROME", letters: ["C","H","R","O","M","E","A","N","T","S"] },
    { word: "CIRCLE", letters: ["C","I","R","C","L","E","A","N","T","S"] },
    { word: "CLASSY", letters: ["C","L","A","S","S","Y","E","N","T","R"] },
    { word: "CLIENT", letters: ["C","L","I","E","N","T","A","S","R","B"] },
    { word: "CLEVER", letters: ["C","L","E","V","E","R","A","N","T","S"] },
    { word: "CLOSET", letters: ["C","L","O","S","E","T","A","N","R","I"] },
    { word: "COBALT", letters: ["C","O","B","A","L","T","E","N","R","S"] },
    { word: "COMBAT", letters: ["C","O","M","B","A","T","E","N","R","S"] },
    { word: "COMET", letters: ["C","O","M","E","T","A","N","R","S","L"] },
    { word: "COMPEL", letters: ["C","O","M","P","E","L","A","N","R","S"] },
    { word: "COPPER", letters: ["C","O","P","P","E","R","A","N","S","T"] },
    { word: "CORNER", letters: ["C","O","R","N","E","R","A","S","T","L"] },
    { word: "COTTON", letters: ["C","O","T","T","O","N","A","E","R","S"] },
    { word: "COYOTE", letters: ["C","O","Y","O","T","E","A","N","R","S"] },
    { word: "CRADLE", letters: ["C","R","A","D","L","E","N","T","S","I"] },
    { word: "CRAFTY", letters: ["C","R","A","F","T","Y","E","N","S","L"] },
    { word: "CREDIT", letters: ["C","R","E","D","I","T","A","N","S","L"] },
    { word: "CRIMSON", letters: ["C","R","I","M","S","O","N","A","E","T"] },
    { word: "CRISPS", letters: ["C","R","I","S","P","S","A","E","T","N"] },
    { word: "CRUISE", letters: ["C","R","U","I","S","E","A","N","T","L"] },
    { word: "CRUNCH", letters: ["C","R","U","N","C","H","A","E","T","S"] },
    { word: "CURVED", letters: ["C","U","R","V","E","D","A","N","T","S"] },
    { word: "DAGGER", letters: ["D","A","G","G","E","R","N","T","S","L"] },
    { word: "DAMPEN", letters: ["D","A","M","P","E","N","R","T","S","L"] },
    { word: "DANCER", letters: ["D","A","N","C","E","R","T","S","L","I"] },
    { word: "DANGER", letters: ["D","A","N","G","E","R","T","S","L","I"] },
    { word: "DAPPER", letters: ["D","A","P","P","E","R","N","T","S","L"] },
    { word: "DARKER", letters: ["D","A","R","K","E","R","N","T","S","L"] },
    { word: "DAWDLE", letters: ["D","A","W","D","L","E","N","T","S","R"] },
    { word: "DEPORT", letters: ["D","E","P","O","R","T","A","N","S","L"] },
    { word: "DESERT", letters: ["D","E","S","E","R","T","A","N","L","I"] },
  ],
  hard: [
    { word: "BALANCE", letters: ["B","A","L","A","N","C","E","R","T","S"] },
    { word: "BLANKET", letters: ["B","L","A","N","K","E","T","R","S","I"] },
    { word: "BLOSSOM", letters: ["B","L","O","S","S","O","M","A","E","T"] },
    { word: "CABINET", letters: ["C","A","B","I","N","E","T","R","S","L"] },
    { word: "CAMPING", letters: ["C","A","M","P","I","N","G","E","T","S"] },
    { word: "CAPTION", letters: ["C","A","P","T","I","O","N","E","R","S"] },
    { word: "CAPTAIN", letters: ["C","A","P","T","A","I","N","E","R","S"] },
    { word: "CAPTURE", letters: ["C","A","P","T","U","R","E","N","S","L"] },
    { word: "CARAMEL", letters: ["C","A","R","A","M","E","L","N","T","S"] },
    { word: "CARTOON", letters: ["C","A","R","T","O","O","N","E","S","L"] },
    { word: "CASCADE", letters: ["C","A","S","C","A","D","E","N","T","R"] },
    { word: "CHAMBER", letters: ["C","H","A","M","B","E","R","N","T","S"] },
    { word: "CHANNEL", letters: ["C","H","A","N","N","E","L","R","T","S"] },
    { word: "CHAPTER", letters: ["C","H","A","P","T","E","R","N","S","L"] },
    { word: "CHARTER", letters: ["C","H","A","R","T","E","R","N","S","L"] },
    { word: "CHICKEN", letters: ["C","H","I","C","K","E","N","A","T","S"] },
    { word: "CHIMNEY", letters: ["C","H","I","M","N","E","Y","A","T","S"] },
    { word: "CIRCUIT", letters: ["C","I","R","C","U","I","T","A","E","N"] },
    { word: "CLAIMED", letters: ["C","L","A","I","M","E","D","N","T","S"] },
    { word: "CLARITY", letters: ["C","L","A","R","I","T","Y","E","N","S"] },
    { word: "CLASSIC", letters: ["C","L","A","S","S","I","C","E","N","T"] },
    { word: "CLIMATE", letters: ["C","L","I","M","A","T","E","N","S","R"] },
    { word: "CLUSTER", letters: ["C","L","U","S","T","E","R","A","N","I"] },
    { word: "COASTAL", letters: ["C","O","A","S","T","A","L","E","N","R"] },
    { word: "COBWEBB", letters: ["C","O","B","W","E","B","B","A","N","T"] },
    { word: "COINAGE", letters: ["C","O","I","N","A","G","E","R","T","S"] },
    { word: "COLOGNE", letters: ["C","O","L","O","G","N","E","A","T","S"] },
    { word: "COLUMNS", letters: ["C","O","L","U","M","N","S","A","E","T"] },
    { word: "COMBINE", letters: ["C","O","M","B","I","N","E","A","T","S"] },
    { word: "COMPETE", letters: ["C","O","M","P","E","T","E","A","N","S"] },
    { word: "COMPILE", letters: ["C","O","M","P","I","L","E","A","N","T"] },
    { word: "CONCEPT", letters: ["C","O","N","C","E","P","T","A","S","L"] },
    { word: "CONCERN", letters: ["C","O","N","C","E","R","N","A","T","S"] },
    { word: "CONCEAL", letters: ["C","O","N","C","E","A","L","T","S","R"] },
    { word: "CONFIRM", letters: ["C","O","N","F","I","R","M","A","E","T"] },
    { word: "CONTEND", letters: ["C","O","N","T","E","N","D","A","S","L"] },
    { word: "CONTEST", letters: ["C","O","N","T","E","S","T","A","R","L"] },
    { word: "CONTEXT", letters: ["C","O","N","T","E","X","T","A","S","R"] },
    { word: "CONTROL", letters: ["C","O","N","T","R","O","L","A","E","S"] },
    { word: "CONVERT", letters: ["C","O","N","V","E","R","T","A","S","L"] },
    { word: "COOKING", letters: ["C","O","O","K","I","N","G","A","E","T"] },
    { word: "COOLING", letters: ["C","O","O","L","I","N","G","A","E","T"] },
    { word: "CORRECT", letters: ["C","O","R","R","E","C","T","A","N","S"] },
    { word: "COTTAGE", letters: ["C","O","T","T","A","G","E","N","R","S"] },
    { word: "COURAGE", letters: ["C","O","U","R","A","G","E","N","T","S"] },
    { word: "COVERED", letters: ["C","O","V","E","R","E","D","A","N","T"] },
    { word: "CRYSTAL", letters: ["C","R","Y","S","T","A","L","E","N","I"] },
    { word: "CULTURE", letters: ["C","U","L","T","U","R","E","A","N","S"] },
    { word: "CURRENT", letters: ["C","U","R","R","E","N","T","A","S","L"] },
    { word: "CURTAIN", letters: ["C","U","R","T","A","I","N","E","S","L"] },
    { word: "CUSHION", letters: ["C","U","S","H","I","O","N","A","E","T"] },
  ],
  daily: [
    { word: "AMBER", letters: ["A","M","B","E","R","N","T","S"] },
    { word: "BLAZE", letters: ["B","L","A","Z","E","N","T","S"] },
    { word: "CRISP", letters: ["C","R","I","S","P","A","E","T"] },
    { word: "DRIFT", letters: ["D","R","I","F","T","A","E","S"] },
    { word: "EMBER", letters: ["E","M","B","E","R","A","N","T"] },
    { word: "FLAIR", letters: ["F","L","A","I","R","E","N","T"] },
    { word: "GLINT", letters: ["G","L","I","N","T","A","E","S"] },
    { word: "HAVEN", letters: ["H","A","V","E","N","R","T","S"] },
    { word: "IRATE", letters: ["I","R","A","T","E","N","S","L"] },
    { word: "JOUST", letters: ["J","O","U","S","T","A","E","N"] },
    { word: "KNACK", letters: ["K","N","A","C","K","E","T","S"] },
    { word: "LANCE", letters: ["L","A","N","C","E","R","T","S"] },
    { word: "MAPLE", letters: ["M","A","P","L","E","R","N","T"] },
    { word: "NOBLE", letters: ["N","O","B","L","E","A","R","T"] },
    { word: "ORBIT", letters: ["O","R","B","I","T","A","E","N"] },
    { word: "PEARL", letters: ["P","E","A","R","L","N","T","S"] },
    { word: "QUART", letters: ["Q","U","A","R","T","E","N","S"] },
    { word: "RAVEN", letters: ["R","A","V","E","N","T","S","L"] },
    { word: "SCOUT", letters: ["S","C","O","U","T","A","E","N"] },
    { word: "THORN", letters: ["T","H","O","R","N","A","E","S"] },
    { word: "UMBRA", letters: ["U","M","B","R","A","E","N","T"] },
    { word: "VAPOR", letters: ["V","A","P","O","R","E","N","T"] },
    { word: "WHIRL", letters: ["W","H","I","R","L","A","E","T"] },
    { word: "XENON", letters: ["X","E","N","O","N","A","T","S"] },
    { word: "YACHT", letters: ["Y","A","C","H","T","E","N","S"] },
    { word: "ZONAL", letters: ["Z","O","N","A","L","E","R","T"] },
    { word: "ALARM", letters: ["A","L","A","R","M","E","N","T"] },
    { word: "BADGE", letters: ["B","A","D","G","E","N","T","S"] },
    { word: "CEDAR", letters: ["C","E","D","A","R","N","T","S"] },
    { word: "DEPOT", letters: ["D","E","P","O","T","A","N","S"] },
    { word: "ELBOW", letters: ["E","L","B","O","W","A","N","T"] },
    { word: "FRAIL", letters: ["F","R","A","I","L","E","N","T"] },
    { word: "GRAIL", letters: ["G","R","A","I","L","E","N","T"] },
    { word: "HASTE", letters: ["H","A","S","T","E","N","R","L"] },
    { word: "INDEX", letters: ["I","N","D","E","X","A","T","S"] },
    { word: "JOINT", letters: ["J","O","I","N","T","A","E","S"] },
    { word: "KNEEL", letters: ["K","N","E","E","L","A","T","S"] },
    { word: "LASER", letters: ["L","A","S","E","R","N","T","I"] },
    { word: "MANOR", letters: ["M","A","N","O","R","E","T","S"] },
    { word: "NERVE", letters: ["N","E","R","V","E","A","T","S"] },
    { word: "ONSET", letters: ["O","N","S","E","T","A","R","L"] },
    { word: "PANEL", letters: ["P","A","N","E","L","R","T","S"] },
    { word: "QUILL", letters: ["Q","U","I","L","L","A","E","T"] },
    { word: "REALM", letters: ["R","E","A","L","M","N","T","S"] },
    { word: "SPINE", letters: ["S","P","I","N","E","A","T","R"] },
    { word: "TWIRL", letters: ["T","W","I","R","L","A","E","N"] },
    { word: "ULTRA", letters: ["U","L","T","R","A","E","N","S"] },
    { word: "VISOR", letters: ["V","I","S","O","R","A","E","T"] },
    { word: "WALTZ", letters: ["W","A","L","T","Z","E","N","S"] },
    { word: "YEARN", letters: ["Y","E","A","R","N","T","S","L"] },
  ]
};

// Get today's daily puzzle seeded by date
function getDailyPuzzle() {
  const today = new Date();
  const seed = today.getFullYear() * 10000 + (today.getMonth() + 1) * 100 + today.getDate();
  const index = seed % PUZZLES.daily.length;
  return PUZZLES.daily[index];
}

// Get puzzles for a difficulty, shuffled
function getPuzzles(difficulty) {
  if (difficulty === 'daily') return [getDailyPuzzle()];
  const list = [...PUZZLES[difficulty]];
  // Fisher-Yates shuffle
  for (let i = list.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [list[i], list[j]] = [list[j], list[i]];
  }
  return list;
}
