const PUZZLES = {
  easy: [
    { letters:['S','T','A','R','E'], validWords:['STARE','TEARS','RATES','ASTER','TARES'] },
    { letters:['S','T','E','A','M'], validWords:['STEAM','MATES','TEAMS','MEATS'] },
    { letters:['L','E','A','S','T'], validWords:['LEAST','STEAL','TALES','STALE','SLATE'] },
    { letters:['B','R','A','I','N'], validWords:['BRAIN','BAIRN'] },
    { letters:['P','A','R','T','S'], validWords:['PARTS','TRAPS','STRAP'] },
    { letters:['E','A','R','T','H'], validWords:['EARTH','HEART','HATER'] },
    { letters:['A','N','G','L','E'], validWords:['ANGEL','ANGLE','GLEAN'] },
    { letters:['L','I','V','E','S'], validWords:['LIVES','EVILS','VEILS'] },
    { letters:['S','P','A','C','E'], validWords:['SPACE','CAPES','PACES'] },
    { letters:['S','P','O','R','T'], validWords:['SPORT','PORTS','STROP'] },
    { letters:['S','C','A','L','E'], validWords:['SCALE','LACES'] },
    { letters:['S','W','O','R','D'], validWords:['SWORD','WORDS'] },
    { letters:['R','A','N','G','E'], validWords:['RANGE','ANGER'] },
    { letters:['T','R','A','C','E'], validWords:['TRACE','CRATE','CATER','REACT'] },
    { letters:['P','A','N','E','L'], validWords:['PANEL','PLANE','PENAL'] },
    { letters:['C','L','E','A','N'], validWords:['CLEAN','LANCE'] },
    { letters:['C','H','A','R','M'], validWords:['CHARM','MARCH'] },
    { letters:['D','R','I','V','E'], validWords:['DRIVE','DIVER'] },
    { letters:['C','H','E','S','T'], validWords:['CHEST','TECHS'] },
    { letters:['S','N','A','R','E'], validWords:['SNARE','EARNS','NEARS','SANER'] },
    { letters:['S','W','E','A','T'], validWords:['SWEAT','WASTE'] },
    { letters:['B','E','L','O','W'], validWords:['BELOW','BOWEL','ELBOW'] },
    { letters:['P','A','R','S','E'], validWords:['PARSE','SPARE','REAPS','PEARS'] },
    { letters:['L','A','T','E','R'], validWords:['LATER','ALTER','ALERT'] },
    { letters:['G','R','O','A','N'], validWords:['GROAN','ORANG','ORGAN'] },
    { letters:['S','T','R','A','W'], validWords:['STRAW','WARTS'] },
    { letters:['S','P','I','N','E'], validWords:['SPINE','PINES','SNIPE'] },
    { letters:['R','I','S','E','N'], validWords:['RISEN','RINSE','REINS','SIREN'] },
    { letters:['L','I','T','E','R'], validWords:['LITER','LITRE','TILER'] },
    { letters:['S','T','O','N','E'], validWords:['STONE','TONES','NOTES','ONSET'] },
    { letters:['S','M','I','L','E'], validWords:['SMILE','SLIME','MILES','LIMES'] },
    { letters:['S','P','O','R','E'], validWords:['SPORE','ROPES','POSER','PROSE'] },
    { letters:['O','P','T','I','C'], validWords:['OPTIC','TOPIC'] },
    { letters:['N','I','G','H','T'], validWords:['NIGHT','THING'] },
    { letters:['S','H','O','R','E'], validWords:['SHORE','HORSE'] },
    { letters:['M','O','I','S','T'], validWords:['MOIST','OMITS'] },
    { letters:['D','E','P','O','T'], validWords:['DEPOT','OPTED'] },
    { letters:['I','N','E','R','T'], validWords:['INERT','INTER','TRINE'] },
    { letters:['S','H','A','R','E'], validWords:['SHARE','SHEAR','HARES','HEARS'] },
    { letters:['T','H','E','R','E'], validWords:['THERE','THREE'] },
    { letters:['F','L','O','W','S'], validWords:['FLOWS','FOWLS','WOLFS'] },
    { letters:['F','L','A','R','E'], validWords:['FLARE','FERAL'] },
    { letters:['G','L','A','R','E'], validWords:['GLARE','LAGER','LARGE','REGAL'] },
    { letters:['S','T','E','E','L'], validWords:['STEEL','SLEET'] },
    { letters:['O','T','H','E','R'], validWords:['OTHER','THROE'] },
    { letters:['C','O','R','N','S'], validWords:['CORNS','SCORN'] },
    { letters:['S','C','O','R','E'], validWords:['SCORE','CORES'] },
    { letters:['C','L','A','S','P'], validWords:['CLASP','CLAPS','SCALP'] },
    { letters:['S','T','O','R','E'], validWords:['STORE','ROTES'] },
    { letters:['B','R','I','D','E'], validWords:['BRIDE','REBID'] },
  ],
  medium: [
    { letters:['C','A','R','E','T','S'], validWords:['CARETS','CRATES','REACTS','TRACES','CASTER','CATERS'] },
    { letters:['S','T','R','E','A','M'], validWords:['STREAM','MASTER','TAMERS'] },
    { letters:['L','I','S','T','E','N'], validWords:['LISTEN','SILENT','ENLIST','TINSEL','INLETS'] },
    { letters:['H','O','R','N','E','T'], validWords:['HORNET','THRONE'] },
    { letters:['P','L','A','N','E','T'], validWords:['PLANET','PLATEN'] },
    { letters:['C','A','S','T','L','E'], validWords:['CASTLE','CLEATS','ECLATS'] },
    { letters:['S','T','A','R','V','E'], validWords:['STARVE','AVERTS','VASTER'] },
    { letters:['F','L','O','W','E','R'], validWords:['FLOWER','FOWLER','REFLOW'] },
    { letters:['S','I','L','V','E','R'], validWords:['SILVER','LIVERS','SLIVER'] },
    { letters:['P','A','R','E','N','T'], validWords:['PARENT','ENTRAP','TREPAN'] },
    { letters:['D','A','N','C','E','R'], validWords:['DANCER','CRANED'] },
    { letters:['L','A','M','E','N','T'], validWords:['LAMENT','MENTAL'] },
    { letters:['I','N','E','R','T','S'], validWords:['SINTER','INERTS','NITERS','INSERT'] },
    { letters:['C','O','R','S','E','T'], validWords:['CORSET','ESCORT','SECTOR'] },
    { letters:['T','R','A','N','C','E'], validWords:['TRANCE','NECTAR','RECANT'] },
    { letters:['S','N','O','R','E','D'], validWords:['SNORED','DRONES'] },
    { letters:['S','T','E','R','O','L'], validWords:['STEROL','OSTLER'] },
    { letters:['P','O','R','I','N','G'], validWords:['PORING','ROPING'] },
    { letters:['M','O','R','S','E','L'], validWords:['MORSEL','MORELS'] },
    { letters:['G','A','R','D','E','N'], validWords:['GARDEN','DANGER','RANGED','GANDER'] },
    { letters:['C','A','L','M','E','R'], validWords:['CALMER','MARCEL'] },
    { letters:['B','U','S','T','L','E'], validWords:['BUSTLE','BLUEST','SUBLET','SUBTLE'] },
    { letters:['C','H','A','N','T','S'], validWords:['CHANTS','SNATCH'] },
    { letters:['W','I','N','T','E','R'], validWords:['WINTER','TWINER'] },
    { letters:['F','A','S','T','E','R'], validWords:['FASTER','AFTERS','STRAFE'] },
    { letters:['S','T','R','I','K','E'], validWords:['STRIKE','TRIKES'] },
    { letters:['S','T','A','R','E','D'], validWords:['STARED','TRADES','TREADS'] },
    { letters:['L','O','A','D','E','R'], validWords:['LOADER','ORDEAL','RELOAD'] },
    { letters:['S','T','A','B','L','E'], validWords:['STABLE','TABLES','ABLEST','BLEATS'] },
    { letters:['S','H','A','R','E','D'], validWords:['SHARED','SHADER','DASHER'] },
    { letters:['G','R','A','P','E','S'], validWords:['GRAPES','GASPER','GAPERS'] },
    { letters:['P','R','A','I','S','E'], validWords:['PRAISE','ASPIRE'] },
    { letters:['L','O','V','E','R','S'], validWords:['LOVERS','SOLVER'] },
    { letters:['W','A','T','E','R','S'], validWords:['WATERS','WASTER','RAWEST'] },
    { letters:['P','L','E','A','S','E'], validWords:['PLEASE','ASLEEP','ELAPSE'] },
    { letters:['S','T','R','O','K','E'], validWords:['STROKE','STOKER'] },
    { letters:['S','C','A','L','E','D'], validWords:['SCALED','DECALS'] },
    { letters:['N','O','T','I','C','E'], validWords:['NOTICE','NOETIC'] },
    { letters:['P','I','L','O','T','S'], validWords:['PILOTS','PISTOL','SPOILT'] },
    { letters:['B','R','E','A','K','S'], validWords:['BREAKS','BAKERS'] },
    { letters:['L','A','T','H','E','S'], validWords:['LATHES','HASLET'] },
    { letters:['S','C','R','A','P','E'], validWords:['SCRAPE','CAPERS','PACERS','RECAPS'] },
    { letters:['E','N','T','R','A','L'], validWords:['RENTAL','LEARNT','ANTLER'] },
    { letters:['S','P','R','E','A','D'], validWords:['SPREAD','DRAPES','RASPED','SPARED'] },
    { letters:['H','A','V','E','R','S'], validWords:['SHAVER','HAVERS'] },
    { letters:['T','A','S','T','E','R'], validWords:['TASTER','TATERS','TETRAS'] },
    { letters:['C','A','R','V','E','S'], validWords:['CARVES','CAVERS','CRAVES'] },
    { letters:['R','A','N','G','E','R'], validWords:['RANGER','GARNER'] },
    { letters:['T','O','W','E','R','S'], validWords:['TOWERS','STOWER'] },
    { letters:['P','A','R','L','E','Y'], validWords:['PARLEY','REPLAY','PEARLY'] },
  ],
  hard: [
    { letters:['S','T','R','A','N','G','E'], validWords:['STRANGE','GARNETS'] },
    { letters:['P','A','I','N','T','E','R'], validWords:['PAINTER','PERTAIN','REPAINT'] },
    { letters:['N','A','S','T','I','E','R'], validWords:['NASTIER','RETAINS','RETINAS'] },
    { letters:['P','L','A','S','T','E','R'], validWords:['PLASTER','PSALTER','STAPLER','PALTERS'] },
    { letters:['S','C','A','R','L','E','T'], validWords:['SCARLET','CARTELS','CLARETS'] },
    { letters:['G','L','I','S','T','E','N'], validWords:['GLISTEN','TINGLES','SINGLET'] },
    { letters:['D','E','T','R','A','I','N'], validWords:['DETRAIN','TRAINED'] },
    { letters:['C','E','R','T','A','I','N'], validWords:['CERTAIN','TACRINE'] },
    { letters:['L','O','A','D','E','R','S'], validWords:['LOADERS','ORDEALS','RELOADS'] },
    { letters:['L','E','A','S','I','N','G'], validWords:['LEASING','SEALING'] },
    { letters:['K','I','T','C','H','E','N'], validWords:['KITCHEN','THICKEN'] },
    { letters:['T','E','A','R','I','N','G'], validWords:['TEARING','INGRATE','GRANITE','TANGIER'] },
    { letters:['T','R','E','A','S','O','N'], validWords:['TREASON','SENATOR','ATONERS'] },
    { letters:['P','A','N','T','I','E','S'], validWords:['PANTIES','SAPIENT','PATINES'] },
    { letters:['P','I','R','A','T','E','S'], validWords:['PIRATES','TRAIPSE'] },
    { letters:['S','A','L','T','I','E','R'], validWords:['SALTIER','SALTIRE','REALIST','TAILERS'] },
    { letters:['S','T','A','C','K','E','R'], validWords:['STACKER','RESTACK'] },
    { letters:['T','R','O','U','N','C','E'], validWords:['TROUNCE','CORNUTE'] },
    { letters:['C','I','N','D','E','R','S'], validWords:['CINDERS','DISCERN','RESCIND'] },
    { letters:['H','U','N','T','E','R','S'], validWords:['HUNTERS','SHUNTER'] },
    { letters:['C','L','A','I','M','E','D'], validWords:['CLAIMED','MEDICAL'] },
    { letters:['D','E','P','O','S','I','T'], validWords:['DEPOSIT','TOPSIDE'] },
    { letters:['O','U','T','S','I','D','E'], validWords:['OUTSIDE','TEDIOUS'] },
    { letters:['D','E','N','S','I','T','Y'], validWords:['DENSITY','DESTINY'] },
    { letters:['S','L','A','N','D','E','R'], validWords:['SLANDER','DARNELS'] },
    { letters:['M','O','T','H','E','R','S'], validWords:['MOTHERS','THERMOS','SMOTHER'] },
    { letters:['P','O','S','T','U','R','E'], validWords:['POSTURE','PETROUS','SPOUTER'] },
    { letters:['G','A','R','D','E','N','S'], validWords:['GARDENS','DANGERS','GANDERS'] },
    { letters:['S','P','O','R','T','E','D'], validWords:['SPORTED','DEPORTS'] },
    { letters:['M','A','R','B','L','E','S'], validWords:['MARBLES','BLAMERS'] },
    { letters:['E','N','A','M','O','R','S'], validWords:['ENAMORS','OARSMEN'] },
    { letters:['S','M','A','R','T','E','N'], validWords:['SMARTEN','MARTENS'] },
    { letters:['H','O','S','T','I','L','E'], validWords:['HOSTILE','EOLITHS'] },
    { letters:['P','A','S','T','I','M','E'], validWords:['PASTIME','IMPASTE'] },
    { letters:['P','A','S','T','U','R','E'], validWords:['PASTURE','UPRATES'] },
    { letters:['M','I','N','S','T','E','R'], validWords:['MINSTER','MINTERS'] },
    { letters:['S','P','E','C','T','R','A'], validWords:['SPECTRA','CARPETS'] },
    { letters:['I','G','N','O','R','E','S'], validWords:['IGNORES','REGIONS'] },
    { letters:['R','O','A','S','T','E','D'], validWords:['ROASTED','TORSADE'] },
    { letters:['P','E','L','I','C','A','N'], validWords:['PELICAN','CAPELIN'] },
    { letters:['M','I','N','E','R','A','L'], validWords:['MINERAL','MARLINE'] },
    { letters:['P','A','R','L','E','Y','S'], validWords:['PARLEYS','PLAYERS','REPLAYS'] },
    { letters:['H','A','L','T','E','R','S'], validWords:['HALTERS','LATHERS','SLATHER'] },
    { letters:['C','A','L','M','E','S','T'], validWords:['CALMEST','CAMLETS'] },
    { letters:['O','U','T','L','I','N','E'], validWords:['OUTLINE','ELUTION'] },
    { letters:['S','T','E','R','I','L','E'], validWords:['STERILE','LEISTER'] },
    { letters:['C','R','E','A','T','E','D'], validWords:['CREATED','REACTED','CATERED'] },
    { letters:['T','A','N','G','L','E','S'], validWords:['TANGLES','LAST','GELANTS'] },
    { letters:['S','T','O','R','I','E','S'], validWords:['STORIES','SORTIES'] },
    { letters:['R','E','L','A','T','E','S'], validWords:['RELATES','RESTATE','STEALER','EALTERS'] },
  ],
  daily: [
    { letters:['A','M','B','E','R'], validWords:['AMBER','BREAM','EMBAR'] },
    { letters:['B','L','A','Z','E'], validWords:['BLAZE'] },
    { letters:['C','R','I','S','P'], validWords:['CRISP'] },
    { letters:['D','R','I','F','T'], validWords:['DRIFT'] },
    { letters:['F','L','A','I','R'], validWords:['FLAIR','FRAIL'] },
    { letters:['G','L','I','N','T'], validWords:['GLINT'] },
    { letters:['H','A','V','E','N'], validWords:['HAVEN'] },
    { letters:['J','O','U','S','T'], validWords:['JOUST'] },
    { letters:['L','A','N','C','E'], validWords:['LANCE','CLEAN','ECLAT'] },
    { letters:['M','A','P','L','E'], validWords:['MAPLE'] },
    { letters:['N','O','B','L','E'], validWords:['NOBLE'] },
    { letters:['P','E','A','R','L'], validWords:['PEARL'] },
    { letters:['R','A','V','E','N'], validWords:['RAVEN'] },
    { letters:['S','C','O','U','T'], validWords:['SCOUT'] },
    { letters:['T','H','O','R','N'], validWords:['THORN'] },
    { letters:['V','A','P','O','R'], validWords:['VAPOR'] },
    { letters:['W','H','I','R','L'], validWords:['WHIRL'] },
    { letters:['Y','A','C','H','T'], validWords:['YACHT'] },
    { letters:['S','T','A','R','E'], validWords:['STARE','TEARS','RATES','ASTER','TARES'] },
    { letters:['E','A','R','T','H'], validWords:['EARTH','HEART','HATER'] },
    { letters:['S','T','O','N','E'], validWords:['STONE','TONES','NOTES','ONSET'] },
    { letters:['G','L','A','R','E'], validWords:['GLARE','LAGER','LARGE','REGAL'] },
    { letters:['S','P','I','N','E'], validWords:['SPINE','PINES','SNIPE'] },
    { letters:['S','M','I','L','E'], validWords:['SMILE','SLIME','MILES','LIMES'] },
    { letters:['T','R','A','C','E'], validWords:['TRACE','CRATE','CATER','REACT'] },
    { letters:['P','A','R','S','E'], validWords:['PARSE','SPARE','REAPS','PEARS'] },
    { letters:['S','H','A','R','E'], validWords:['SHARE','SHEAR','HARES','HEARS'] },
    { letters:['R','I','S','E','N'], validWords:['RISEN','RINSE','REINS','SIREN'] },
    { letters:['L','A','T','E','R'], validWords:['LATER','ALTER','ALERT'] },
    { letters:['C','L','A','S','P'], validWords:['CLASP','CLAPS','SCALP'] },
  ]
};

function getDailyPuzzle() {
  const today = new Date();
  const seed = today.getFullYear() * 10000 + (today.getMonth() + 1) * 100 + today.getDate();
  return PUZZLES.daily[seed % PUZZLES.daily.length];
}

function getPuzzles(difficulty) {
  if (difficulty === 'daily') return [getDailyPuzzle()];
  const list = [...PUZZLES[difficulty]];
  for (let i = list.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [list[i], list[j]] = [list[j], list[i]];
  }
  return list;
}
